### ISSUE TITLE
BUG: An error in the name of the examples-unused-resources/peristent-volumes directory

### ISSUE THREAD

**Issue by AllaouaA** [gianlucam76/k8s-cleaner#105]
# Problem Description

The link in the readme.md to the unused-resources example of PersistentVolumes does not work https://github.com/gianlucam76/k8s-cleaner/tree/main/examples-unused-resources/presistent-volumes (error 404).
In fact there is a typo in the link and in the directory name https://github.com/gianlucam76/k8s-cleaner/tree/main/examples-unused-resources/peristent-volumes it should be "persistent" instead of "persitent"

**Comment by AllaouaA** [comment]
sorry, I made a mistake with the label, it's not really a bug but just a typo in the documentation

**Comment by gianlucam76** [comment]
Thank you @AllaouaA 

Fixed it.
