### ISSUE TITLE
BUG: Controller POD CrashLoopBackError

### ISSUE THREAD

**Issue by mikecarr** [gianlucam76/k8s-cleaner#23]
# Problem Description
I just tried to insall this on my k8s cluster, the controlller pod is in CarshLoopBackoff with error:  exec /manager: exec format error

Command used to install: 
```
kubectl apply -f https://raw.githubusercontent.com/gianlucam76/k8s-cleaner/main/manifest/manifest.yaml
```

Am I doing something wrong?

# System Information

Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.4

# Logs

```
k logs k8s-cleaner-controller-5c979bdc5-9cwct
exec /manager: exec format error
```

All nods running on Ubuntu Jammy
```
cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="[https://www.ubuntu.com/"](https://www.ubuntu.com/%22)
SUPPORT_URL="[https://help.ubuntu.com/"](https://help.ubuntu.com/%22)
BUG_REPORT_URL="[https://bugs.launchpad.net/ubuntu/"](https://bugs.launchpad.net/ubuntu/%22)
PRIVACY_POLICY_URL="[https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"](https://www.ubuntu.com/legal/terms-and-policies/privacy-policy%22)
UBUNTU_CODENAME=jammy
```

**Comment by gianlucam76** [comment]
Thank @mikecarr. Sorry about that. looking at it now.

**Comment by gianlucam76** [comment]
Hi @mikecarr, reproduced and fixed it. I had uploaded wrong image :-(

If you delete the pod it should fetch the new image (please edit deployment with imagePullPolicy: Always so it gets new image)
