### ISSUE TITLE
Scaledown deployments if all pods have more than 1000 restarts

### ISSUE THREAD

**Issue by grzesrap** [gianlucam76/k8s-cleaner#45]
Please give example of auto-stop applications with over 1000 restarts. 
This action should take place if all Pods in DP have more than 1000 restarts per Pod

**Comment by gianlucam76** [comment]
Thank you for filing this request!

Added a [Cleaner instance](https://github.com/gianlucam76/k8s-cleaner/blob/main/unhealthy-resources-examples/deployments/scale-down-high-restart-deployment.yaml) that identifies and removes unhealthy Deployments in the 
Kubernetes cluster based on pod restarts.

Unhealthy definition: A Deployment is considered unhealthy if all its Pods have 
each container restarted at least 50 times.

Action: When an unhealthy Deployment is found, it will be automatically  scaled 
down to zero replicas (effectively removing it).
