### ISSUE TITLE
helm chart

### ISSUE THREAD

**Issue by oliverbaehler** [gianlucam76/k8s-cleaner#59]
**Describe the solution you'd like**
Are you interested in distributing k8s-cleaner as helm chart? I can contribute that. :)

**Comment by gianlucam76** [comment]
Thank you @oliverbaehler 

I would love that. If you have time to help with it, I would very much appreciate your help/contribution.

**Comment by oliverbaehler** [comment]
@gianlucam76 No problem, that's bread and butter for me
