### ISSUE TITLE
BUG: Can't use custom namespace when applying the controller

### ISSUE THREAD

**Issue by hamza-m-masood** [gianlucam76/k8s-cleaner#82]
# Problem Description

_INSTRUCTIONS: Describe the problem in as much detail as possible, including the actions which caused the problem, and any other information you believe would be helpful in reproducing the problem._

The docs give the following method of applying the controller
```
kubectl apply -f https://raw.githubusercontent.com/gianlucam76/k8s-cleaner/main/manifest/manifest.yaml
```

The file contains hardcoded values for a namespaces. When I use my own name, I get the following errors:
```
namespace/projectsveltos created
customresourcedefinition.apiextensions.k8s.io/cleaners.apps.projectsveltos.io unchanged
customresourcedefinition.apiextensions.k8s.io/reports.apps.projectsveltos.io unchanged
clusterrole.rbac.authorization.k8s.io/k8s-cleaner-controller-role unchanged
clusterrole.rbac.authorization.k8s.io/k8s-cleaner-metrics-reader unchanged
clusterrole.rbac.authorization.k8s.io/k8s-cleaner-proxy-role unchanged
clusterrolebinding.rbac.authorization.k8s.io/k8s-cleaner-controller-rolebinding unchanged
clusterrolebinding.rbac.authorization.k8s.io/k8s-cleaner-proxy-rolebinding unchanged
the namespace from the provided object "projectsveltos" does not match the namespace "k8s-cleaner". You must pass '--namespace=projectsveltos' to perform this operation.
the namespace from the provided object "projectsveltos" does not match the namespace "k8s-cleaner". You must pass '--namespace=projectsveltos' to perform this operation.
the namespace from the provided object "projectsveltos" does not match the namespace "k8s-cleaner". You must pass '--namespace=projectsveltos' to perform this operation.

```

# System Information

_INSTRUCTIONS: Provide the system and application information below._

CLUSTERAPI VERSION: ` [e.g. v1.2.4 etc.] `
SVELTOS VERSION: ` [e.g. PRODUCT version X.Y.Z] `
KUBERNETES VERSION: ` [e.g. v1.25 etc.] `

# Logs

_INSTRUCTIONS: Provide any additional information you think would be helpful below.  Large files, logs, etc. can be attached to this issue so long as they meet the GitHub attachment guidelines described here: https://help.github.com/en/github/managing-your-work-on-github/file-attachments-on-issues-and-pull-requests_

``
[insert additional information here]
``

**Comment by gianlucam76** [comment]
As of now, k8s-cleaner needs to be installed in the "projectsveltos" namespace. 

Might I ask why that is a problem? I can make it generic but for now that is a requirement.

**Comment by gianlucam76** [comment]
Thank you @hamza-m-masood It makes sense

For now you need to download the manifest you will have to manually change. For instance to use "test" as namespace

wget https://raw.githubusercontent.com/gianlucam76/k8s-cleaner/main/manifest/manifest.yaml 
sed -i -e 's/namespace: projectsveltos/namespace: test/g' manifest.yaml
sed -i -e 's/name: projectsveltos/name: test/g' manifest.yaml

kubectl apply -f manifest.yaml

**Comment by hamza-m-masood** [comment]
@gianlucam76 by the way I just installed the helm chart and I am able to specify a custom namespace.

**Comment by gianlucam76** [comment]
Thanks @hamza-m-masood 

Can we then close this? It is not easy to make namespace configurable in yaml. There is a ClusterRoleBinding so namespace must be known or expressed as a template. So not ideal for a YAML.
