### ISSUE TITLE
Create a Helm chart

### ISSUE THREAD

**Issue by hamza-m-masood** [gianlucam76/k8s-cleaner#85]
**Is your feature request related to a problem? Please describe.**

Please create a helm chart for this operator so it is easier for users to install and maintain.

**Comment by gianlucam76** [comment]
There is already an Helm chart (though probably we don't have in the README) 

@oliverbaehler added it.

https://github.com/gianlucam76/k8s-cleaner/tree/main/charts/k8s-cleaner

**Comment by gianlucam76** [comment]
I will let @oliverbaehler answer that (I don't want to risk giving an incorrect answer)

**Comment by hamza-m-masood** [comment]
@oliverbaehler I see from the log output of the github actions that the helm repo is this: `oci://ghcr.io/gianlucam76/charts/k8s-cleaner`

But I am not able to run `helm repo add` using this link. Is there a link I could use `helm repo add` or `helm pull` with? I need such a link so I can integrate this operator in our CI pipeline. Thanks.

**Comment by oliverbaehler** [comment]
```
helm install k8s-cleaner oci://ghcr.io/gianlucam76/charts/k8s-cleaner --version 0.4.0   -n k8s-cleaner --create-namespace
```

@gianlucam76 btw on the repo you can enable packages on the repo. Then the chart package it will be displayed on the right site of the repository
